name: Build and Push Docker Image to GHCR
on:
  push:
    branches:
      - main # Trigger on pushes to main branch
  pull_request:
    branches:
      - main # Trigger on PRs targeting the main branch
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3
      # Step 2: Set up Docker Buildx (for multi-platform builds)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      # Step 3: Log in to GitHub Container Registry (GHCR)
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }} # Uses GitHub username
          password: ${{ secrets.GITHUB_TOKEN }} # Uses the automatically provided GitHub token
      # Step 4: Get short commit SHA (optional)
      - name: Get short commit SHA
        id: sha
        run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
      # Step 5: Build and Push Docker image for multi-platform (ARM and AMD64)
      - name: Build and Push Docker image
        run: |
          docker buildx build \
            --platform linux/arm64,linux/amd64 \
            -t ghcr.io/${{ github.repository_owner }}/eggman:latest \
            --push .
