name: Build and Update Manifests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    outputs:
      short_sha: ${{ steps.get-sha.outputs.short_sha }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - id: get-sha
        name: Get short commit SHA
        run: |
          echo "short_sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: Build and Push Docker image
        run: |
          docker buildx build \
            --platform linux/arm64,linux/amd64 \
            -t ghcr.io/${{ github.repository_owner }}/eggman:${{ steps.get-sha.outputs.short_sha }} \
            --push .

  update-manifest:
    name: Update Manifests in External Repo
    needs: build-and-push
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/eggman
      KUSTOMIZATION_PATH: apps/eggman/overlays/prod/kustomization.yaml
    steps:
      - uses: actions/checkout@v3
        with:
          repository: bergtobias/homelab-infra
          ref: main
          token: ${{ secrets.GH_OPS_TOKEN }}
      - run: |
          curl -sSfL https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv5.0.1/kustomize_v5.0.1_linux_amd64.tar.gz \
            | tar xz -C /usr/local/bin
          chmod +x /usr/local/bin/kustomize
      - run: |
          cd $(dirname $KUSTOMIZATION_PATH)
          kustomize edit set image "${IMAGE_NAME}:${{ needs.build-and-push.outputs.short_sha }}"
      - run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add $KUSTOMIZATION_PATH
          if git diff --cached --quiet; then
            exit 0
          fi
          git commit -m "ci: bump eggman image to ${{ needs.build-and-push.outputs.short_sha }} [skip ci]"
          git push origin main
