name: Build and Push Docker Image to GHCR
on:
  push:
    branches:
      - main # Trigger on pushes to main branch
  pull_request:
    branches:
      - main # Trigger on PRs targeting the main branch
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        # Step 2: Set up Docker Buildx (for multi-platform builds)

        uses: docker/setup-buildx-action@v2
      - name: Log in to GitHub Container Registry
        # Step 3: Log in to GitHub Container Registry (GHCR)

        uses: docker/login-action@v2
        with:
          username: ${{ github.actor }} # Uses GitHub username
          password: ${{ secrets.GITHUB_TOKEN }} # Uses the automatically provided GitHub token
      - name: Get short commit SHA
        # Step 4: Get short SHA for the image tag

        id: sha
        run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
      - name: Build Docker image
        # Step 5: Build Docker image with short SHA tag

        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/eggman:${{ env.SHORT_SHA }} .
      - name: Push Docker image to GHCR
        # Step 6: Push Docker image to GHCR

        run: |
          docker push ghcr.io/${{ github.repository_owner }}/eggman:${{ env.SHORT_SHA }}
